In [4]:
import numpy

In [5]:
import numpy as np

In [6]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(array)

print(type(array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Arrays Creation

## 0-D Arrays

In [7]:
import numpy as np

array = np.array(42)

print(array)

42


## 1-D Arrays

In [8]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

print(array)

[1 2 3 4 5]


## 2-D Arrays

In [9]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

print(array)

[[1 2 3]
 [4 5 6]]


## 3-D arrays

In [10]:
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(array)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


## Number of Dimensions

In [11]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


# NumPy Array Indexing

# Access Array Elements

You can access an array element by referring to its index number.

## NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [12]:
import numpy as np

array = np.array([1, 2, 3, 4])

print(array[0])
print(array[1])


1
2


## Access 2-D Arrays

In [14]:
import numpy as np

array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st: ', array[0, 1])

print('5th element on 2nd: ', array[1, 4])

2nd element on 1st:  2
5th element on 2nd:  10


## Access 3-D Arrays

In [16]:
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(array[0, 1, 2])

6


## Negative Indexing
### Use negative indexing to access an array from the end.

In [18]:
import numpy as np

array = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd : ', array[1, -1])


Last element from 2nd :  10


# NumPy Array Slicing

## Slicing arrays

### We pass slice instead of index like this: [start:end].

### We can also define the step, like this: [start:end:step].


In [19]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[1:5])


print(array[4:])


print(array[:4])



[2 3 4 5]
[5 6 7]
[1 2 3 4]


## Negative Slicing

In [20]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7])

print(array[-3:-1])

[5 6]


## STEP

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


print(arr[::2])


[2 4]
[1 3 5 7]


## Slicing 2-D Arrays

In [22]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

print(arr[0:2, 2])

print(arr[0:2, 1:4])

[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


# NumPy Data Types

In [23]:
import numpy as np

arrayint = np.array([1, 2, 3, 4])

print(arrayint.dtype)

arrayString = np.array(['apple', 'banana', 'cherry'])

print(arrayString.dtype)

int32
<U6


## Arrays With a Defined Data Type

In [25]:
import numpy as np

array = np.array([1, 2, 3, 4], dtype='S')

print(array)
print(array.dtype)

array = np.array([1, 2, 3, 4], dtype='i4')

print(array)
print(array.dtype)

[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32


## Converting Data Type on Existing Arrays

In [29]:
import numpy as np

array = np.array([1.1, 2.1, 3.1])

newarr = array.astype('i')

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [27]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = array.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


# Array COPY

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


# Array view

In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# NumPy Array Shape

In [35]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(array.shape)

array = np.array([1, 2, 3, 4], ndmin=5)

print(array)
print('shape of array :', array.shape)

(2, 4)
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


# NumPy Array Reshaping


## Reshape From 1-D to 2-D

In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = array.reshape(4, 3)

print(newarr)

## Reshape From 1-D to 3-D

In [36]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = array.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# NumPy Array Iterating

## 1-D array

In [37]:
import numpy as np

array = np.array([1, 2, 3])

for x in arr:
  print(x)


1
2
3


## 2-D Arrays

In [39]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)


for x in arr:
  for y in x:
    print(y)


[1 2 3]
[4 5 6]
1
2
3
4
5
6


## 3-D Arrays

In [40]:
import numpy as np

array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)


for x in arr:
  for y in x:
    for z in y:
      print(z)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [42]:
import numpy as np

array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(array):
  print(x)


1
2
3
4
5
6
7
8


## Iterating With Different Step Size

In [46]:
import numpy as np

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(array[:, ::2]):
  print(x)


1
3
5
7


## Iteration Using ndenumerate()

In [47]:
import numpy as np

array = np.array([1, 2, 3])

for idx, x in np.ndenumerate(array):
  print(idx, x)

array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(array):
  print(idx, x)


(0,) 1
(1,) 2
(2,) 3
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# NumPy Joining Array

## NumPy Arrays

### concatenate() 

In [49]:
import numpy as np

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.concatenate((array1, array2))

print(array)

[1 2 3 4 5 6]


##  Two 2-D arrays 

In [50]:
import numpy as np

array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

array = np.concatenate((array1, array2), axis=1)

print(array)

[[1 2 5 6]
 [3 4 7 8]]


## Joining Arrays Using Stack Functions

In [51]:
import numpy as np

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.stack((array1, array2), axis=1)

print(array)

[[1 4]
 [2 5]
 [3 6]]


## Stacking Along Rows

In [52]:
import numpy as np

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.hstack((array1, array2))

print(array)


[1 2 3 4 5 6]


## Stacking Along Columns

In [53]:
import numpy as np

array1 = np.array([1, 2, 3])

array2 = np.array([4, 5, 6])

array = np.vstack((array1, array2))

print(array)

[[1 2 3]
 [4 5 6]]


# NumPy Splitting Array

## Splitting NumPy Arrays

In [55]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(array, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


## Using hsplit() opposite of hstack()

In [57]:
import numpy as np

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(array, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays

## use the where() method

In [62]:
import numpy as np

array = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(array == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


## Search Sorted searchsorted()

In [63]:
import numpy as np

array = np.array([6, 7, 8, 9])

x = np.searchsorted(array, 7)

print(x)

1


## Search From the Right Side

In [64]:
import numpy as np

array = np.array([6, 7, 8, 9])

x = np.searchsorted(array, 7, side='right')

print(x)


2


## Multiple Values

In [65]:
import numpy as np

array = np.array([1, 3, 5, 7])

x = np.searchsorted(array, [2, 4, 6])

print(x)

[1 2 3]


# NumPy Sorting Arrays

In [66]:
import numpy as np

array = np.array([3, 2, 0, 1])

print(np.sort(array))

[0 1 2 3]


## Sorting a 2-D Array

In [68]:
import numpy as np

array = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(array))


[[2 3 4]
 [0 1 5]]


## Random Numbers in NumPy

In [69]:
from numpy import random

x = random.randint(100)

print(x)

69


In [70]:
from numpy import random

x = random.rand()

print(x)

0.7049207893062581


In [71]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[95 92 83 12 24]


In [72]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[59 54 92 36  5]
 [74 88 24 96 70]
 [23 79 13 74 16]]


In [73]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


In [74]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 7 9 3 3]
 [5 7 5 5 9]
 [9 5 3 7 7]]
